Create Visual Studio 2022 solution and projects for each utility
hgruniaux/hashutils pull request #1
Opened 2022-08-09 00:09 UTC by kpieckiel

Added cryptopp as a submodule and created a VS 2022 solution that contains the cryptopp cryptlib project and a project for each hash utility.

2022-08-09 09:41 UTC, hgruniaux requested changes
Thanks for the pull request!

Some remarks:
 - Actually the project `md2sum` do not compile. See the comments on msvc/md2sum.vcxproj
 - Maybe modify the CMakeLists.txt to use the git submodule instead of a vcpkg package for cryptopp if you want.

2022-08-09 09:41 UTC, hgruniaux commented on msvc/md2sum.vcxproj
> +    <ClCompile Include="..\..\..\Private\hashtest\src\utils.cpp" />
This should be changed to `<ClCompile Include="..\src\utils.cpp" />`

2022-08-09 09:41 UTC, hgruniaux commented on msvc/md2sum.vcxproj
> +    <ClInclude Include="..\..\..\Private\hashtest\src\utils.hpp" />
Same here `<ClInclude Include="..\src\utils.hpp" />`

2022-08-12 22:25 UTC, kpieckiel commented
I love peer review--thanks for catching that!  I had included those files from the wrong project directory.  This has been updated and all projects should compile now.

2022-08-14 19:22 UTC, merged

2022-08-14 19:22 UTC, hgruniaux commented
Thanks for your time and effort !